name: Deploy plugins.json to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 创建 deploy 文件夹，只放 plugins.json
      - name: Prepare plugins.json for Pages
        run: |
          mkdir deploy
          cp dist/plugins.json deploy/plugins.json

      # 3. 上传 deploy 文件夹到 Pages（使用最新版 upload-pages-artifact v3）
      - name: Upload plugins.json
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # 4. 部署到 GitHub Pages（使用最新 deploy-pages v4）
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
